apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: myapp-pipeline
spec:
  params:
    - name: app-name
      type: string
      default: myapp
    - name: build-image
      type: string
      default: image-registry.openshift-image-registry.svc:5000/sn-labs-aloysiusric0/myapp:latest
    - name: repo-url
      type: string
      description: Git repository URL

  workspaces:
    - name: output

  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: output

    - name: git-clone
      runAfter: [cleanup]
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
      workspaces:
        - name: output
          workspace: output

    - name: flake8
      runAfter: [git-clone]
      taskRef:
        name: flake8
      workspaces:
        - name: source
          workspace: output

    - name: nose
      runAfter: [flake8]
      taskRef:
        name: nose
      workspaces:
        - name: source
          workspace: output

    - name: buildah
      runAfter: [nose]
      taskRef:
        name: buildah
      params:
      - name: IMAGE
        value: $(params.build-image)
      workspaces:
        - name: source
          workspace: output

    - name: oc-client
      runAfter: [buildah]
      taskRef:
        name: oc-client
      params:
        - name: app-name
          value: $(params.app-name)
        - name: build-image
          value: $(params.build-image)
      workspaces:
        - name: source
          workspace: output
